name = "SimpleStringScanners"
uuid = "fe2b3641-c6e9-460c-8da8-2838146e3f25"
authors = ["Hiroharu Sugawara <hsugawa@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
